### ISSUE TITLE
Build does not work anymore

### ISSUE THREAD

**Issue by Galveston01** [WebThingsIO/addon-list#1088]
Hi,

I hope this is the right place to describe my problem. @mrstegeman should know about the context. 

I just wanted to create a new release for the Macros add-on, but the action fails:
```
Unable to find image 'mozillaiot/toolchain-linux-arm-node-8:latest' locally
docker: Error response from daemon: pull access denied for mozillaiot/toolchain-linux-arm-node-8, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
```
I tried using this docker container locally, which happens to fail as well. I then looked [here](https://hub.docker.com/u/mozillaiot) and realized that this container does not seem to exist. But only about a week ago, everything worked fine, so the container was still there back then, right?

Do I missunderstand something here or is the image really gone?

Best regards

**Comment by tim-hellhake** [comment]
Hi @Galveston01

All docker images moved to the `webthingsio` organization.
You need to replace `mozillaiot/toolchain-linux-arm-node-8` with `webthingsio/toolchain-linux-arm-node-8`.
After that everything should work again :)

**Comment by Galveston01** [comment]
Hi @tim-hellhake,

Oh well this totally makes sense, I probably should have thought of this myself🙈. Seems to be working again now, thanks :)
