### ISSUE TITLE
Voco has been updated to 2.4.0

### ISSUE THREAD

**Issue by createcandle** [WebThingsIO/addon-list#1222]
It now has more robust satellite functionality. If the main server changes IP, then a satellite can do a simple network scan to rediscover it, and then reconnect.

**Comment by mrstegeman** [comment]
I don't see a new release: https://github.com/createcandle/voco/releases

**Comment by createcandle** [comment]
I thought it was stable, but then after a day a satellite stopped working. This may take a few attempts to figure out, but it seems to work now.
