### ISSUE TITLE
MySensors addon has been updated

### ISSUE THREAD

**Issue by createcandle** [WebThingsIO/addon-list#1239]
Added RGB support after a user asked for it.

**Comment by mrstegeman** [comment]
In the future, please just open a PR with the updates. You can find the checksums attached to your release, e.g. https://github.com/createcandle/Webthings-mysensors-adapter/releases/tag/1.2.2.

**Comment by createcandle** [comment]
I'm not sure I understand. You mean in the JSON file for the addon?

So should I manually copy and paste every sha-sum into the json file? That's over 20 files.

**Comment by mrstegeman** [comment]
Yes. That part is not automated, so it has to be done manually, either by you or me.

Alternatively, I believe @tim-hellhake has a script he's been using to do this, but he has not yet shared it with me. 😉

**Comment by createcandle** [comment]
whoa 0_0
