### ISSUE TITLE
JSON generator tool

### ISSUE THREAD

**Issue by createcandle** [WebThingsIO/addon-list#1249]
I've created a small tool that ingests a Github JSON releases page, and turns it into JSON for the addon list.

It can be found at: 
https://webthingsgateway.com/jsontool/

 It currently only works for python based addons, but it should be easy to modify the code to also work for javascript based addons. Source can be found here:
https://gist.github.com/createcandle/196e09a84e20fbff8dbe7a92d7530be2

I just used it to created a new release for the MySensors addon.

**Comment by mrstegeman** [comment]
Just FYI, GitHub provides a nice API for such things: https://docs.github.com/en/rest/reference/repos#releases

I'm going to close the issue, but thanks for posting this!
