### ISSUE TITLE
Voco has been updated

### ISSUE THREAD

**Issue by createcandle** [WebThingsIO/addon-list#1252]
It seems the github scripts don't generate the extra files as with the mysensors addon? (no shasum file, for example)

I've attempted to use the shasum from my local development server to create a pull request, but i wasn't sure what file to point to. I've pointed it to a tar file I've uploaded to my own server.

**Comment by mrstegeman** [comment]
The `.sha256sum` file is attached to the release, as expected: https://github.com/createcandle/voco/releases/tag/2.5.2

**Comment by createcandle** [comment]
Ah I guess it just takes a while. Thanks.
