### ISSUE TITLE
UI extension with javascript addon?

### ISSUE THREAD

**Issue by flatsiedatsie** [WebThingsIO/addon-list#1264]
Are there any existing javascript-based addons that extend the UI? I'm looking for an example of how to implement this, because I would like to explore adding a network visualisation and device update feature to the Zigbee2MQTT addon.

**Comment by mrstegeman** [comment]
https://github.com/WebThingsIO/example-adapter

**Comment by flatsiedatsie** [comment]
Yes I ended up using that. It seems there are no existing javascript addons that have implemented this fully.

**Comment by mrstegeman** [comment]
This add-on also extends the UI: https://github.com/WebThingsIO/webhook-events

**Comment by flatsiedatsie** [comment]
`this.showBackButton('/things');`

Cool!
