### ISSUE TITLE
Candle Manager Release script isn't triggering?

### ISSUE THREAD

**Issue by createcandle** [WebThingsIO/addon-list#1321]
The last two releases didn't generate the extra files somehow:

https://github.com/createcandle/Candle-manager-addon/releases

**Comment by mrstegeman** [comment]
You forgot to update the version string in `manifest.json`: https://github.com/createcandle/Candle-manager-addon/blob/master/manifest.json#L73

**Comment by createcandle** [comment]
Thanks for yur sharp eye.
