### ISSUE TITLE
new LIFX mini color not being found

### ISSUE THREAD

**Issue by edwoody** [WebThingsIO/addon-list#1457]
Hi, I have LIFX bulbs (color and white) that have worked for years.  Lately I bought new, both color and white and webthings LIFX add-on doesn't find them.  Returned, bought another just in case.  Same thing with new plain white bulb.  Doesn't show up after a scan.  Just a note.  Thanks.

**Comment by benfrancis** [comment]
Hi, thanks for reporting this. Could you please report this issue in the lifx-adapter repo https://github.com/tim-hellhake/lifx-adapter/issues
