### ISSUE TITLE
webthings addon didn'T update

### ISSUE THREAD

**Issue by arist0v** [WebThingsIO/addon-list#1482]
i had the date time adapter version 1.2.1 currently installed, 

i also have removed and resintalled it but still version 1.2.1

i looked at the date time adapter repo and the addon-list repo

both are on 1.2.3 (python 3.7) but i still can't have the latest version from the addon on webthings

**Comment by hwine** [comment]
fwiw, 1.2.3 should be offered per #1481 -- unless there is a separate step to publish the latest production branch.

**Comment by wfahle** [comment]
I'm not sure why the 1.2.1 is still active, 1.2.3 was merged in. Do I need to make an update as 1.3.x to get it to pull the latest?

**Comment by arist0v** [comment]
Usually, once the addon pr is merged, you don't have anything to do, it's
live immediately

Le lun. 14 nov. 2022, 12 h 58, William Fahle ***@***.***> a
écrit :

**Comment by wfahle** [comment]
Further information: If you hit this api endpoint, it returns a list of all the addons available. For whatever reason, it still lists version 1.2.1 for date-time-adapter. https://api.webthings.io:8443/addons?arch=linux-arm&version=1.1.0&node=64&python=2.7,3.7

**Comment by tim-hellhake** [comment]
It's `1.2.3` now.
I guess it was a caching problem.
@arist0v can you please check if it works now?

**Comment by wfahle** [comment]
Looks right on my setup now. Thanks.

**Comment by arist0v** [comment]
i still have 1.2.1

i restarted the server and still on 1.2.1 

i deleted and reinstall, and still 1.2.1

**Comment by wfahle** [comment]
Oops, I was looking at my manual install. It still looks wrong to me. When I click the above link I see: `""id":"date-time-adapter","name":"DateTime Adapter","description":"A Date & Time adapter to create more advanced rules using sunrise, sunset, weekends, etc.","author":"tomasy-wfahle","homepage_url":"https:\/\/github.com\/WTIOAddons\/date-time-adapter","license_url":"https:\/\/raw.githubusercontent.com\/WTIOAddons\/date-time-adapter\/main\/LICENSE","version":"1.2.1","url":"https:\/\/github.com\/WTIOAddons\/date-time-adapter\/releases\/download\/v1.2.1\/date-time-adapter-1.2.1-linux-arm-v3.7.tgz","checksum":"6f4bf5a7aa7250c0bc4e93bde4dca5bd82a30b933e1a4880011a6cf095273752","primary_type":"adapter"},{"id":"dingz-adapter","name":"Dingz","description":"Dingz support","author":"Martin Giger","homepage_url":"https:\/\/github.com\/freaktechnik\/dingz-adapter","license_url":"https:\/\/raw.githubusercontent.com\/freaktechnik\/dingz-"`

**Comment by arist0v** [comment]
update now available!
