### ISSUE TITLE
"Egress is over the account limit"

### ISSUE THREAD

**Issue by flatsiedatsie** [WebThingsIO/addon-list#1484]
I was installing the ESP-Home adapter, and got a 400 error. I tried opening the github download link to the esphome-adapter-0.2.2.tgz file manually, and noticed this error message.

```
<Code>ServerBusy</Code>
<Message>Egress is over the account limit.  etc
```

I then tried to install an addon from my own account, and that worked. I guess Tim's addons are very popular? :-)

**Comment by benfrancis** [comment]
Thanks for reporting.

This download link seems to be working for me https://github.com/tim-hellhake/esphome-adapter/releases/download/0.2.2/esphome-adapter-0.2.2.tgz and I can successfully install the add-on on WebThings Gateway.

Is anyone else able to reproduce the problem?

**Comment by tim-hellhake** [comment]
The cause was an internal GitHub quota.
There is nothing we can do about it.
